# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.4
      - test-1.5
jobs:
  test-1.4: &test-template
    docker:
      - image: circleci/elixir:1.4

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
              - compile-cache

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix credo --strict
      - run: mix dogma
      - run: mix coveralls.html

      - store_artifacts:
          path: cover/excoveralls.html
          destination: coverage.html

      - run: mix dialyzer --halt-exit-status

      - save_cache:
          key: compile-cache
          paths:
              - _build
              - deps
  test-1.5:
    <<: *test-template
    docker:
      - image: circleci/elixir:1.5
